### ISSUE TITLE
niebieska wersja dla 1.8 luty 2020

### ISSUE THREAD

**Issue by edmib1** [MastaNub/paczka#12]
Siemanowice Śląskie, mam problem otóż na spisie txt do pobrania w sekcji stare jest wersja 1.8 luty 2020, i jest ona tylko w wersji różowej, czy znajdzie sie może taka sama w wersji niebieskiej? pozdrawiam

**Comment by MastaNub** [comment]
Sierpień 2020? To jest ta sama paczka.
https://github.com/MastaNub/paczka/raw/master/Old/%C2%A7bOverlay%20Grafa%20%C2%A7a1.8%20%C2%A7fSierpie%C5%84%202020.zip

**Comment by edmib1** [comment]
chodzi mi o to by był taki sam overlay jak w wersji luty lecz z klasyczny kolorem diamentów a nie różowym, a wersja sierpniowa jest odnowiona pod względem overlaya ;-;

**Comment by MastaNub** [comment]
Znalazłem tylko tą z 2019
[1.8 blue.zip](https://github.com/MastaNub/paczka/files/6075204/1.8.blue.zip)

**Comment by edmib1** [comment]
chyba to właśnie ta, dzięki wielkie <3
