### ISSUE TITLE
Niebieski txt dla wersji 1.15 z lutego 2020

### ISSUE THREAD

**Issue by Kubix321** [MastaNub/paczka#13]
Siema mam pytanie czy macie jeszcze wersję niebieską paczki z lutego 2020 bo jest taka wersja w zakładce stare wersje ale kolor txt jest różowy a ja bym chciał bardzo ten niebieski. To jest ten txt co Graf używał przez prawie cały sezon 3 km tak btw.

**Comment by MastaNub** [comment]
to było na 1.14
https://github.com/MastaNub/paczka/raw/master/Old/%C2%A76Overlay%20Grafa%20%C2%A7a1.14.4%20%C2%A7fListopad%202019.zip
czyli to

**Comment by Kubix321** [comment]
To jest stara wersja chyba jedna z pierwszych tej paczki a mi chodziło o "overlay grafa luty 2020 1.15" wersja niebieska wersja chyba miała w sobie cursed chickeny cursed wilki i miał zielony
 Hotbar a ta ma przezroczysty. O btw ta paczka z listopada straszliwie laguje to chyba jest jakiś bug.

**Comment by txtgrafa** [comment]
@Kubix321 z lutego nie ma wersji niebieskiej, wtedy była edycja walentynkowa i zostały udostępnione paczki różowe.
Wersja 1.15 z sierpnia jest niebieska, też chciałbym wspomnieć ze początek nazwy paczki decyduje o kolorze, jeśli jest na początku §b to bedzie niebieska, jeśli §d to różowa

**Comment by MastaNub** [comment]
dzieki

**Comment by Kubix321** [comment]
Wiem że temat już dawno skończony ale chciałbym powiedzieć że ten txt był na starej stronie grafa uhc.yt i nie jestem pewny ale ta wersja paczki była tak pół oficjalna.
