### ISSUE TITLE
nie działający random 

### ISSUE THREAD

**Issue by chrishoranq** [MastaNub/paczka#4]
Masta napraw sans granie na wersji 1.16.2 bo po prostu się nie pokazuję enchant table w książce nawet zmieniłem wartość z 10% na 99 a i tak nie było widać chyba że specjalnie tak zrobiłeś żeby tego widać nie było 
(na wersjach 1.15.2, 1.16.2 nie widać na 100%)

**Comment by MastaNub** [comment]
1.15 i 1.16 jest upośledzone jeżeli chodzi o optifine
będę na to patrzył za dniach

**Comment by MastaNub** [comment]
https://github.com/sp614x/optifine/issues/5392
To błąd Optifine.
