### ISSUE TITLE
Nie ma różowego txt 

### ISSUE THREAD

**Issue by Dominalix** [MastaNub/paczka#7]
nie ma różowego txt masta pls napraw to

**Comment by MastaNub** [comment]
Różowy nie był oficjalny. Był niedokończony i brakowało kilku rzeczy.

**Comment by Dominalix** [comment]
A mógłbyś mi go wysłać, jeśli jeszcze masz go na komie? Bo znudził mi się
niebieski, a nie chce mi się go przerabiać.

sob., 2 sty 2021 o 23:24 masta <notifications@github.com> napisał(a):

**Comment by MastaNub** [comment]
już jest
