### ISSUE TITLE
Nie ma efektów zaklęć na netherytowe itemy

### ISSUE THREAD

**Issue by Ojbyczq** [MastaNub/paczka#9]
Nie ma efektów zaklęć na netherytowe itemy. Chciałbym wiedzieć dlaczego ich nie ma w txt jak na diamentowe są. Masta pls odpisz.

**Comment by MastaNub** [comment]
Bo ta paczka jest na 1.15

**Comment by Ojbyczq** [comment]
> Bo ta paczka jest na 1.15

Ale jest i na 1.16 oraz większość osób będzie grało na 1.16 niż 1.15.

Oczywiście nie mówię żeby koniecznie dodawać efekty zaklęć na neth ity do paczki 
Tylko myślę że jak dodasz do txt to może paczka będzie lepsza (moja opinia btw)

**Comment by MastaNub** [comment]
ale jak ktoś ma netherite to jest wymaxowany
